spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/survey_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
